sudo: required
dist: trusty
language: python
python: 3.6
cache:
  directories:
    - /usr/local/var/pyenv/versions/
before_install:
  - sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev
  - git clone https://github.com/yyuu/pyenv.git ~/.pyenv
  - PYENV_ROOT="$HOME/.pyenv"
  - PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv install 3.6.5
  - pyenv install 3.5.6
  - pyenv install 3.4.9
  - pyenv install 2.7.15
  - pyenv local 3.6.5 3.5.6 3.4.9 2.7.15
install:
  - pip install black coveralls tox
  - pyenv rehash
  - coverage erase
script:
  - tox
  - black . --check
afeter_success:
  - coverage combine
  - coverage report
  - coveralls
