sudo: required
dist: xenial
language: generic
before_install:
  - sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev
  - git clone https://github.com/yyuu/pyenv.git ~/.pyenv
  - PYENV_ROOT="$HOME/.pyenv"
  - PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv install 2.7.16
  - pyenv install 3.4.9
  - pyenv install 3.5.7
  - pyenv install 3.6.8
  - pyenv install 3.7.3
  - pyenv local 3.7.3 3.6.8 3.5.7 3.4.9 2.7.16
install:
  - pip install black coveralls tox
  - pyenv rehash
  - coverage erase
script:
  - tox
  - black . --check
afeter_success:
  - coverage combine
  - coverage report
  - coveralls
